export const HotelsActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  FETCH_COLLECTIONS_BY_CITY_ID: "FETCH_COLLECTIONS_BY_CITY_ID",
};
